apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  defaultBackend:
    service:
      name: issues-service
      port:
        number: 3001
  rules:
    - host: localhost
      http:
        paths:
          - path: /issues
            pathType: Prefix
            backend:
              service:
                name:  issues-service
                port:
                  number: 3001
          - path: /productivity
            pathType: Prefix
            backend:
              service:
                name: productivity-service
                port:
                  number: 3004
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: issues-service
                port:
                  number: 3001
